[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "sbsv"
version = "0.2.3"
authors = [
  { name = "Seungheon Han", email = "shhan814@gmail.com" },
]
description = "SBSV: Square Brackets Separated Values"
readme = "README.md"
dynamic = ["license"]
requires-python = ">=3.6.2"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/hsh814/sbsv"
Issues = "https://github.com/hsh814/sbsv/issues"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '\.venv'

[dependency-groups]
dev = [
    "black>=22.8.0",
    "pytest>=7.0.1",
]
