[metadata]
name = sbsv
version = 0.3.1
author = Seungheon Han
author_email = shhan814@gmail.com
description = SBSV: Square Brackets Separated Values
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/hsh814/sbsv
project_urls =
    Issues = https://github.com/hsh814/sbsv/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
packages = sbsv
python_requires = >=3.6.2
include_package_data = false

[options.package_data]
sbsv = *.pyi
