from typing import Any, List, Mapping, Optional, Sequence, Tuple

class NativeParseError(ValueError): ...

def compile_parser(
    schemas: Sequence[str],
    custom_types: Mapping[str, Any],
    row_type: type,
    ignore_unknown: bool = ...,
    ignored_prefix: Optional[str] = ...,
    save_ignored: bool = ...,
) -> Any: ...
def parse_rows(parser: Any, content: str) -> List[Any]: ...
def parse_line(
    parser: Any, line: str, line_number: int = ...
) -> Optional[Any]: ...
def version() -> Tuple[int, int, int]: ...
