from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

class NativeParseError(ValueError): ...

def compile_parser(
    schemas: Sequence[str],
    custom_types: Mapping[str, Any],
    ignore_unknown: bool = ...,
    ignored_prefix: Optional[str] = ...,
    save_ignored: bool = ...,
) -> Any: ...
def parse_rows(parser: Any, content: str) -> List[Tuple[str, Dict[str, Any]]]: ...
def parse_line(
    parser: Any, line: str, line_number: int = ...
) -> Optional[Tuple[str, Dict[str, Any]]]: ...
def version() -> Tuple[int, int, int]: ...
